---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1vfgzglppmvmpur5tdel8unveme94gfde6d8p9y8q4ex272e0kvts2jvez0"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1vfgzglppmvmpur5tdel8unveme94gfde6d8p9y8q4ex272e0kvts2jvez0"
stores:
  yaml:
    indent: 2
