# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.0.0.31:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.0.0.31"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "lyra"
    ipAddress: "10.0.0.6"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/7bde2d947bcb4133a688b0ce4a11f6b76af0f631fc4cd267236e67a240f7b6e1
    controlPlane: true
    networkInterfaces:
      - interface: "enp8s0"
        dhcp: false
        addresses:
          - "10.0.0.6/23"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.0.0.1"
        mtu: 1500
        vip:
          ip: "10.0.0.31"
      - interface: "eno1"
        ignore: true
  - hostname: "crux"
    ipAddress: "10.0.0.7"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/7bde2d947bcb4133a688b0ce4a11f6b76af0f631fc4cd267236e67a240f7b6e1
    controlPlane: true
    networkInterfaces:
      - interface: "enp8s0"
        dhcp: false
        addresses:
          - "10.0.0.7/23"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.0.0.1"
        mtu: 1500
        vip:
          ip: "10.0.0.31"
      - interface: "eno1"
        ignore: true
  - hostname: "vela"
    ipAddress: "10.0.0.8"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/7bde2d947bcb4133a688b0ce4a11f6b76af0f631fc4cd267236e67a240f7b6e1
    controlPlane: true
    networkInterfaces:
      - interface: "enp8s0"
        dhcp: false
        addresses:
          - "10.0.0.8/23"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.0.0.1"
        mtu: 1500
        vip:
          ip: "10.0.0.31"
      - interface: "eno1"
        ignore: true

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  # schematic:
  #   customization:
  #     extraKernelArgs:
  #       - -init_on_alloc # Less security, faster puter
  #       - init_on_alloc=0 # Less security, faster puter
  #       - -init_on_free # Less security, faster puter
  #       - init_on_free=0 # Less security, faster puter
  #       - -selinux # Less security, faster puter
  #       - apparmor=0 # Less security, faster puter
  #       - intel_iommu=on # PCI Passthrough
  #       - iommu=pt # PCI Passthrough
  #       - mitigations=off # Less security, faster puter
  #       - module_blacklist=e1000e # Disable onboard NIC
  #       - security=none # Less security, faster puter
  #       - talos.auditd.disabled=1 # Less security, faster puter
  #       - ipv6.disable=1 # Disable ipv6
  #     systemExtensions:
  #       officialExtensions:
  #         - siderolabs/i915 # Needed for Intel GPUs
  #         - siderolabs/intel-ucode # Microcode updates for Intel CPUs
  #         - siderolabs/nvme-cli # NVMe management tools
  #         - siderolabs/thunderbolt # The 10GbE Networking is a thunderbolt device
  #         - siderolabs/mei # The machine has Intel Management Engine
  #         # See https://longhorn.io/docs/1.10.0/advanced-resources/os-distro-specific/talos-linux-support/#system-extensions
  #         - siderolabs/iscsi-tools
  #         - siderolabs/util-linux-tools
  kernelModules:
    # https://longhorn.io/docs/1.10.0/advanced-resources/os-distro-specific/talos-linux-support/#v2-data-engine
    - name: nvme_tcp
    - name: vfio_pci
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"
