apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:ttnVNfzuCBER285xvJHnnu22EmNUvDOfNRzN7TQjMhdEqQSrajZ3anSZ9NKTYDAiVMMFuEP/95elpOnex6k41vIESLEH0qGsvPk=,iv:9lJrhMjT7SD7ZDREfG0pw8BJW6JPIUqrUz9sbrUbukg=,tag:qkdxB4+OGzeYsmtQ5yi1AA==,type:str]
sops:
  age:
    - recipient: age1vfgzglppmvmpur5tdel8unveme94gfde6d8p9y8q4ex272e0kvts2jvez0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMGFyd05XbjN6NUJZaG1s
        aUZSL0JBbXVadEVrWGxMNDBrVFpiY3BKa3pzCmhWM2R6SXdxOXFtSDN5cHJkODZa
        N2NxbjFic0ZQTGxlMWVOZ3RvOWhhLzgKLS0tIDcrOUpSOXMwRUVwLzdDaXFkQWRB
        dkZNTW4wV3FadDBOb2Vscm9vOG5HNjQKtRd+TAMaB/Qvsk0bFoLeVjwPGk/vlRSA
        ajmnGpF4p2VBz9tO9wAyxLa0NM21XlEQmTRrpmsViaRt8EkwrChCxA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-27T00:17:39Z"
  mac: ENC[AES256_GCM,data:OZGOQvNT3FIXP+PLrGwF85d1OnL59xXepqCIk03ST3354Tk1vVZWUxEBpCtmHC2isjlTkewndRnG7lqu0MY5wDCRglRSWJy7xWglS8cWVAgAiWDnIGrRpaf7FBIqshkSLvwpH+bSeVbFO/GR9jGX664b+D/DYbgb+pXBBXQ6QwI=,iv:vP8gNKQNM18XmgCdlo+vNMb/XbwVAKRQiADZLkdqjss=,tag:BHP+jJEHgtTY0dXHMBmcpg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
